platform :ios, '9.3'

target 'SwiftDemo' do
  use_frameworks!
  # 忽略引入库的所有警告
  inhibit_all_warnings!
  # Pods for LBFM-Swift
  pod 'SnapKit'
  pod 'Kingfisher'
  #tabbar样式
  pod 'ESTabBarController-swift', '~> 2.6.2'
  #banner滚动图片
  pod 'FSPagerView'
  #pod 'Moya'
  pod 'HandyJSON', '~> 4.2.0'
  #pod 'SwiftyJSON'
  # 分页
  pod 'DNSPageView', '~> 1.0.1'
  #跑马灯
  pod 'JXMarqueeView'
  #滚动页
  #pod 'LTScrollView'
  pod 'MJRefresh'
  #消息提示
  #pod 'SwiftMessages','~> 4.1.4'
  pod 'SVProgressHUD'
end
